### ISSUE TITLE
CircleCI clones the latest commit but doesn't seem to use it

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/chef-buildingdb#6]
I've noticed that CircleCI is dutifully cloning the latest commit of Polygon City but that the version which is online on the dev server is still some old commit. Is the node server being restarted during the CircleCI deploy process?

**Comment by bcamper** [comment]
Just my 2 cents: one thing that can be useful is a ping endpoint (often used for health check, I believe we have one already), that can also output the current running sha. I've used that many times to answer the question "what commit is this machine _really_ running???" :)

**Comment by robhawkes** [comment]
Good idea! Peter also mentioned having some kinda of version number somewhere so this'll definitely make things more obvious. I'll get the ping endpoint to output the SHA along with the 200, unless it should behave differently.

**Comment by robhawkes** [comment]
[2b9d12e](https://github.com/polygon-city/building-database/commit/2b9d12e967a6f42da7b9a62c0f7ad75ed8b170cb) outputs the Git SHA along with the 200 response to the ping endpoint – which isn't updating on the dev server when CircleCI builds but when it does we can use it to be sure of a version.

**Comment by baldur** [comment]
@robhawkes I will take a look at this today and see why the system isn't restarting as it should

**Comment by baldur** [comment]
@robhawkes sorry hit the close button by mistake ;)

**Comment by robhawkes** [comment]
Ha, no worries! Let me know if you need anything from me to help here.

**Comment by baldur** [comment]
This should be fixed now it was a problem with assumption the underlying cookbook was making. It updated the path to a directory in an upstart configuration which is not reloaded in a restart call. Fixed by making the path be the symlink to current release rather than the released folder.

Also @robhawkes we need to make sure we know when we push code that is liable to not restart either because of missing dependencies or faulty code. Is there a way to verify this via the command line somehow so we can detect before deploying to server? something we could run on circle.

Also please close this issue once you have verified that it has been solved

**Comment by robhawkes** [comment]
Looks like this is working to me – I committed a change not long after you fixed it and the sha updated on the ping endpoint.

I've not implemented tests yet (which is bad) but they're on the list as it's integral for reliability now we're automating things. I'm not sure about a missing dependency check but something must exist. I'll prioritise these things and open an issue in the other repo as it's kinda important now for us to move forward.
